# Site settings
title: olynews.org
description: ""
baseurl: ""
url: ""
twitter_username: oly_news
github_username:  olynews
google_analytics:

# Build settings
markdown: kramdown
permalink: /posts/:title/
