# Site settings
title: The Percival
description: ""
baseurl: ""
url: ""
twitter_username: oly_news
github_username:  the-percival
google_analytics:

# Build settings
markdown: kramdown
permalink: /posts/:title/
