# Site settings
title: The Percival
description: ""
baseurl: ""
url: ""
twitter_username: percivalnews
github_username:  the-percival
google_analytics:

# Build settings
markdown: kramdown
permalink: /posts/:title/
exclude: [node_modules, js]
